apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
      - name: task-pv-storage
        mountPath: /var/data
  volumes:
  - name: pv-volume
    persistentVolumeClaim:
      claimName: pv-claim
          


